# Generated by Django 3.2.4 on 2021-07-11 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210611_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mark_steel',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='Марка стали'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Запасы'),
        ),
    ]
