# Generated by Django 3.2.5 on 2021-07-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210719_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diametr',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
