# Generated by Django 3.2.4 on 2021-07-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='fio',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
